name: 'Tests: Playground Matrix Resource'

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        php_extensions: xdebug
        coverage_clover: output/clover-${{ github.ref_name }}.xml
        coverage_text: true
        testdox_text: output/testdox-${{ github.ref_name }}.txt
    - name: Make code coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        report: output/clover-${{ github.ref_name }}.xml
        coverage_badge_path: output/coverage-${{ github.ref_name }}.svg
        push_badge: false
    - name: Git push to image-data branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./output
        publish_branch: image-data
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
